- hosts: web_servers
  become: true
  tasks:
    - name: install apache and php for Debian servers
      tags: apache,apache2,debian
      ansible.builtin.apt:
        name: 
         - apache2
         - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Debian"

    - name: install httpd and php for CentOS servers
      tags: centos,httpd
      ansible.builtin.yum:
        name: 
         - httpd
         - php
        state: latest
      when: ansible_distribution == "CentOS"

    - name: copy default html file for site
      tags: apache,apache2,httpd
      ansible.builtin.copy:
       src: /home/admin/webpage/default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
  