---
- hosts: all
  become: true
  tasks:

  - name: update reposiroty index
    apt: 
     update_cache: yes
    when: ansible_distribution == "Ubuntu"
  #  when: ansible_distribution in ["Ubuntu", "Debian"] if you have 2 servers
  # it will work because both servers has apt 

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"
  